site_name: 计算数学/科学计算 WiKi
site_author: Reichtum
site_url: https://github.com/ReichtumQian

# theme:
#     name: 'material'
#     palette:

#     # Light mode
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       primary: pink
#       accent: indigo
#       toggle:
#         icon: material/toggle-switch-off-outline
#         name: Switch to dark mode

#     # Dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       primary: pink
#       accent: blue
#       toggle:
#         icon: material/toggle-switch
#         name: Switch to light mode

theme:
  name: material
  custom_dir: theme
  font: false
  # custom_dir: overrides
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - navigation.tabs

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  - section-index
  # - mkpdfs

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

repo_name: Reichtum/ScientificComputingWiKi
repo_url: https://github.com/ReichtumQian/ScientificComputingWiKi

extra_css:
  - stylesheets/extra.css

nav:
  - 简介:
    - "index.md"
    - 如何贡献: "简介/如何贡献.md"
    - 数学符号表: "简介/数学符号表.md"
    - 资料推荐: "简介/资料推荐.md"
  - 数学基础:
    - "数学基础/数学基础简介.md"
    - 高等代数基础:
      - "数学基础/高等代数基础/高等代数基础简介.md"
    - 一元积分学:
      - "数学基础/一元积分学/一元积分学简介.md"
      - 定积分概念: "数学基础/一元积分学/定积分概念.md"
    - 多元积分学:
      - "数学基础/多元积分学/多元积分学简介.md"
      - 二重积分: "数学基础/多元积分学/二重积分.md"
      - 三重积分: "数学基础/多元积分学/三重积分.md"
    - 常微分方程:
      - "数学基础/常微分方程/常微分方程简介.md"
    - 偏微分方程:
      - "数学基础/偏微分方程/偏微分方程简介.md"
    - 度量空间:
      - "数学基础/度量空间/度量空间简介.md"
    - 赋范线性空间与Banach空间:
      - "数学基础/赋范线性空间与Banach空间/赋范线性空间与Banach空间简介.md"
    - 内积空间与Hilbert空间:
      - "数学基础/内积空间与Hilbert空间/内积空间与Hilbert空间简介.md"
    - Sobolev空间:
      - "数学基础/Sobolev空间/Sobolev空间简介.md"
      - Sobolev空间概念: "数学基础/Sobolev空间/Sobolev空间概念.md"
  - 科学计算工具: 
    - "科学计算工具/科学计算工具简介.md"
    - Matlab: 
      - "科学计算工具/Matlab/Matlab简介.md"
    - Maple:
      - "科学计算工具/Maple/Maple简介.md"
    - Mathematica:
      - "科学计算工具/Mathematica/Mathematica简介.md"
    - Lapack:
      - "科学计算工具/Lapack/Lapack简介.md"
    - Eigen:
      - "科学计算工具/Eigen/Eigen简介.md"
  - 浮点数误差: "浮点数误差/浮点数误差简介.md"
  - 线性方程组求解: 
    - "线性方程组求解/线性方程组求解简介.md"
    - 线性方程组直接法:
      - "线性方程组求解/线性方程组直接法/线性方程组直接法简介.md"
    - 线性方程组迭代法:
      - "线性方程组求解/线性方程组迭代法/线性方程组迭代法简介.md"
  - 函数逼近论: 
    - "函数逼近论/函数逼近论简介.md"
    - 正交多项式逼近: 
      - "函数逼近论/正交多项式逼近/正交多项式逼近简介.md"
      - 正交多项式概念: "函数逼近论/正交多项式逼近/正交多项式概念.md"
      - 正交多项式逼近: "函数逼近论/正交多项式逼近/正交多项式逼近.md"
      - 常用正交多项式: "函数逼近论/正交多项式逼近/常用正交多项式.md"
      - 维尔斯特拉斯定理: "函数逼近论/正交多项式逼近/维尔斯特拉斯定理.md"
    - 最小二乘法:
      - "函数逼近论/最小二乘法/最小二乘法简介.md"
  - 特征值计算: 
    - "特征值计算/特征值计算简介.md"
    - 幂法: "特征值计算/幂法.md"
  - 非线性方程求解: 
    - "非线性方程求解/非线性方程求解简介.md"
    - 二分法: "非线性方程求解/二分法.md"
    - 牛顿法: "非线性方程求解/牛顿法.md"
    - 割线法: "非线性方程求解/割线法.md"
    - 高维牛顿法: "非线性方程求解/高维牛顿法.md"
  - 多项式插值: 
    - "多项式插值/多项式插值简介.md"
    - 单变量多项式插值:
      - "多项式插值/单变量多项式插值/单变量多项式插值简介.md"
    - 样条插值:
      - "多项式插值/样条插值/样条插值简介.md"
    - 多元多项式插值:
      - "多项式插值/多元多项式插值/多元多项式插值简介.md"
  - 数值积分: 
    - "数值积分/数值积分简介.md"
    - 一维数值积分理论: "数值积分/一维数值积分理论.md"
    - 牛顿-柯特斯公式: "数值积分/牛顿-柯特斯公式.md"
    - 复化公式: "数值积分/复化公式.md"
    - 高斯公式: "数值积分/高斯公式.md"
    - 高维牛顿-柯特斯公式: "数值积分/高维牛顿-柯特斯公式.md"
  - 微分方程数值解: "微分方程数值解/微分方程数值解简介.md"
  - 有限元方法: "有限元方法/有限元方法简介.md"